version: "3.9"
services:
  restic:
    image: restic/restic:latest
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RESTIC_HOSTNAME=${RESTIC_HOSTNAME:-host1}
    volumes:
      - ./data:/data:ro
